
--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount)as revenue
from customers
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount from customers where discount_applied = 'Yes' AND purchase_amount >= 
(select avg(purchase_amount)as avg_amount
from customers)

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as avg_rating
from customers
group by item_purchased order by avg_rating desc limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, round(avg(purchase_amount),2) as avg_purchase
from customers
where shipping_type in ('Standard','Express')
group by shipping_type 

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status , count(customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_amount,
sum(purchase_amount) as total_amount
from customers
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, count(*) as total_purchase,
round(100* sum(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/count(*),2) as discount_purchase
from customers
group by item_purchased
order by discount_purchase desc 
limit 5 

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

SELECT 
    COUNT(customer_id) AS customer_count,
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS segments
FROM customers
GROUP BY 
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyer
from customers
where previous_purchases >  5
group by subscription_status

--Q10. What is the revenue contribution of each age group?  

SELECT 
    age_group,
    SUM(purchase_amount) AS revenue,
    ROUND(
        SUM(purchase_amount) * 100.0 / SUM(SUM(purchase_amount)) OVER (), 
        2
    ) AS revenue_percentage
FROM customers
GROUP BY age_group
ORDER BY revenue DESC;
